### ISSUE TITLE
Slight incompatibility with Fargo's Souls mod

### ISSUE THREAD

**Issue by Thatfoxyouknow** [nakano15/terraguardians#7]
everything works fine until you leave a soul in their bag or accessory slots and exit the world, once you do the world no longer loads and the character no longer is able to enter worlds (ever new ones) 

the error:
﻿

X
Main engine crash
Tip: This is likely a mod's fault. Disable mods one by one and check if the issue persists
System.NullReferenceException: Object reference not set to an instance of an object.
at FargowiltasSouls.Core.Toggler SoulCheck.GetToggleValue(Player player, String name, Boolean checkForMutantPresence) in FargowiltasSouls\Core\Toggler\SoulCheck.cs:line 14
at FargowiltasSouls.Content.Items.Accessories Enchantments.PalmWood Enchant PalmEffect(Player player, Item item) in FargowiltasSouls\Content Items\Accessories\Enchantments\PalmWoodEnchant.cs:line 43 at Terraria.ModLoader.ItemLoader.UpdateAccessory(Item item, Player player, Boolean hideVisual) in tModLoader Terraria\ModLoader\ItemLoader.cs:line 1218
at DMD<System.Void Terraria Player:Apply EquipFunctional(Terraria.Item, System.Boolean)>(Player this, Item currentItem, Boolean hideVisual)
at SyncProxy <System.Void Terraria.Player:ApplyEquipFunctional(Terraria.Item, System.Boolean)>(Player, Item, Boolean)
at Terraria Player.UpdateEquips(Int32 i) in tModLoader\Terraria Player.cs:line 10233
at terraguardians.Companion.UpdateEquipments(Boolean Underwater, Boolean RuntModLoaderHooks) in terraguardians\CompanionPlayerMaskScripts.cs:line 1958
at terraguardians.Companion.InitializeCompanion(Boolean Spawn) in terraguardians\Companion.cs:line 2076
at terraguardians.MainMod.SpawnCompanion(Vector2 Position, CompanionData data, Player Owner) in terraguardians\MainMod.cs:line 530
at terraguardians. PlayerMod.CallCompanionByIndex(UInt32 Index, Boolean TeleportIfExists, Boolean Forced) in terraguardians\PlayerMod.cs:line 814
at terraguardians.PlayerMod.OnEnterWorld() in terraguardians\PlayerMod.cs:line 485
at Terraria.ModLoader.PlayerLoader.OnEnterWorld(Int32 playerIndex) in tModLoader\Terraria\ModLoader PlayerLoader.cs:line 1184
at Terraria.Player.Hooks.EnterWorld(Int32 playerIndex) in tModLoader\Terraria\Player.cs:line 280
at Terraria Player.Spawn/PlayerSpawnContext context) in tModLoader\Terraria Player.cs:line 30701
at Terraria.WorldGen. Finish PlayWorld() in tModLoader\Terraria\WorldGen.cs:line 2782
at Terraria.Main.ConsumeAllMainThreadActions() in tModLoader\Terraria\Main.cs:line 14040
at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 14078
at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 546
at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
at Terraria.Program.RunGame() in tModLoader Terraria\Program.cs:line 264
A client.log file containing error information has been generated in S:\Programs (x86)\steamapps\common\tModLoader\tModLoader-Logs (You will need to share this file if asking for help)

**Comment by Thatfoxyouknow** [comment]
i might be able to bring my old guardians out of a back up file if i know what IDE opens their .tgf files, but until then ill just keep them backed up

**Comment by Thatfoxyouknow** [comment]
after leaving a different item from fargo's souls mod on one i can confirm it is any item from the fargo's souls mod not just the one in the error log, same exact error

**Comment by nakano15** [comment]
Sorry for not answering earlier, I'm not used to answer issues here (the count actually gives that away).
That issue is odd, but I have no idea how Fargo Souls mod works. Beside, that mod is known for causing issues with the companions mod, and I have no idea why.

I recommend letting the creator of that mod know of this issue, even more since it seems to break your save.
Meanwhile, you can try disabling the mod and trying to remove the accessory, if that works. As for the soul thing, I doubt the mod will load the soul state from companions, since other mod stuffs that happen on companions aren't saved yet.

Edit: And I doubt you're the fox I know.

**Comment by Thatfoxyouknow** [comment]
ok that worked, the mod keep re-enabling it self due to it being a dependency to another mod and I thought that method just wasn't working.

also its not _every_ item in fargo's souls mod the squeaky duck dose not cause this, thought it was calamity.

thank you for your time!
